$buildTimeoutInMinutes=120
$vmSize="Standard_D2_v2"
$osDiskSizeGB="127"
$PUBLISHER='MicrosoftWindowsDesktop'
$OFFER='office-365'
$SKU='21h1-evd-o365pp'
$sigGalleryName= ""
$sigImageDefName =""
#$sigImageVersion=1.0.0
$runOutputName="sigOutput"
$artifactTags_source=""
$artifactTags_baseosimg="windows10"
$imageTemplateName=""
$OsType="Windows"
$vnetRgName=""
$vnetName=""
$subnetName=""
